name: Release

on:
  push:
    tags:
      - 'v**'
  # eslint-disable-next-line yml/no-empty-mapping-value
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          registry-url: https://registry.npmjs.org/

      - name: Setup
        run: npm i -g @antfu/ni

      - name: Install
        run: nci

      - name: Build & Publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_PUBLISH_TOKEN}}

      - run: npx changelogithub
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
